config/routes.rb
Rails.application.routes.draw do
	# static pages
	root 'static_pages#home'
	get '/about', to: "static_pages#about"
	get '/contact', to: "static_pages#contact"
		
	# users
  get '/signup', to: 'users#new'
	get '/profile', to: 'users#show'
	get '/editprofile', to: 'users#edit'
	resources :users do
		resources :activities
	end
	
	# activities
	resources :activities do
		resources :entries
	end

	# sessions
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

	has_many :entries, dependent: :destroy

	validates :user_id, presence: true
	
	validates :name,	presence: :true,
										uniqueness: { scope: :user,
																	case_sensitive: false } 
	validates :units, presence: true

	before_save { self.name.capitalize! }
	
	def self.create_todays_entry
		activities = self.all
		activities.each do |activity|
			activity.entries.create(date: Date.today, units:0)
		end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
	belongs_to :activity

	validates :activity_id, presence: true
	validates :date, presence: true,
									 uniqueness: { scope: :activity_id }
	validate :date_cannot_be_in_future
	validates :units, { presence: true, numericality: true }

	def date_cannot_be_in_future
		if date > Date.today
			errors.add(:date, "entries can't be made for future dates")
		end
	end

	def self.to_csv
		attributes = %w{date amount}
		CSV.generate(headers: true) do |csv|
			csv << attributes

			all.each do |entry|
				csv << entry.attributes.values_at("date", "units")
			end
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	
	has_many :activities, dependent: :destroy

	validates :name, length: { minimum: 2 }
	validates :email,	presence: true, 
										uniqueness: true,
										format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
	validates :password, length: { minimum: 6 }

	before_save do
		self.email.downcase!
		self.name.capitalize!
	end

	def self.create_new_activity
		user = self.first
		name = Time.now.to_s
		user.activities.create(name: name, units: 'none')
	end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	def new
		@activity = current_user.activities.build
	end

	def create
		@activity = current_user.activities.build(activity_params)
		if @activity.save
			flash[:success] = "New activity has been created"
			redirect_to user_path(current_user)
		else
			render 'new'
		end
	end

  def edit
		@activity = Activity.find(params[:id])
	end

	def update
		@activity = Activity.find(params[:id]) 
		@activity.update_attributes(activity_params)
		redirect_to current_user
	end

  def show
		@activity = current_user.activities.find(params[:id])
		@all_entries = @activity.entries.order(date: :desc)
		@entries = @activity.entries.order(date: :desc).paginate(:page => params[:page], :per_page => 7)
		@plot_data = Array.new
		@activity.entries.order(date: :desc).limit(7).each { |entry| @plot_data.push([entry.date.to_formatted_s(:db),entry.units]) }

		respond_to do |format|
			format.html
			format.csv { send_data @all_entries.to_csv }
		end
  end

	def destroy
		@activity = current_user.activities.find(params[:id])
		@activity.destroy
		redirect_to user_path(current_user)
	end

	private

	def activity_params
		params.require(:activity).permit(:name, :units)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def new
		@activity = Activity.find(params[:activity_id])
		@entry = @activity.entries.build
	end
	def edit
		@activity = Activity.find(params[:activity_id])
		@entry = Entry.find(params[:id])
		respond_to do |f|
			f.html { redirect_to user_activity_path(current_user, @activity) }
			f.js
		end
	end
	def create
		@activity = Activity.find(params[:activity_id])
		@entry = @activity.entries.build(entry_params)
		if @entry.save
			redirect_to activity_path(@activity) 
		else
			render 'new'
		end
	end
	def update
		@activity = Activity.find(params[:activity_id])
		@entry = Entry.find(params[:id])
		@entry.update_attributes(entry_params)
		
		respond_to do |f|
			if @entry.save
				f.html {redirect_to user_activity_path(current_user, @activity)}
				f.js
			else
				f.html {render :new}
			end
		end
	end
	def destroy
		@entry = Entry.find(params[:id]) 
		@entry.destroy
		redirect_to activity_path(Activity.find(params[:activity_id]))
	end
	private

	def entry_params
		params.require(:entry).permit(:date, :activity_id, :units)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
	end

	def create
		user = User.find_by(email: params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			log_in(user)
			redirect_to profile_path
		else
			flash.now[:danger] = "Wrong credentials"
			render 'new'
		end
	end

	def destroy
		session.delete(:user_id)
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

	def about
	end

	def contact
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in, only: [:edit, :show]
  before_action :correct_user, only: [:edit, :show]
		
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)	
		if @user.save
			flash[:success] = "You have successfully signed up."
			log_in(@user)
			redirect_to profile_path
		else
			render 'new'
		end
	end

  def edit
		@user = User.find_by(id: session[:user_id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to profile_path
		else
			render 'edit'
		end
	end

  def show
		@activities = current_user.activities
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def logged_in
		unless logged_in?
			flash[:danger] = "Please Log In"
			redirect_to login_path
		end
	end

	def correct_user
		@user = User.find_by(id: session[:user_id])
		unless current_user?(@user)
			redirect_to profile_path
			flash[:danger] = "You do not have access to that page!"
		end
	end
end

app/helpers/activites_helper.rb
module ActivitesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def full_title(page_title = "")
		base_title = "Creature of Habit"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end
	def current_user?(user)
		user == current_user
	end
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	def logged_in?
		!current_user.nil?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_new_activity.html.erb
<%= form_for [@user,@activity], remote: true do |f| %>
	<%= render 'shared/error_messages', object: @activity %>

	<%= f.text_field :name, placeholder: "Name of Activity", class: "form-control" %>
	<br>
	<%= f.text_field :units, placeholder: "What units to use?", class: "form-control" %>

	<%= f.submit "Create", class: "btn btn-default" %>
	<%= link_to "Cancel", current_user, class: "btn btn-default" %>

<% end %>

app/views/activities/edit.html.erb
<h3>Edit <%= @activity.name %></h3>

	<%= form_for [@user,@activity] do |f| %>
		<%= render 'shared/error_messages', object: @activity %>

		<%= f.text_field :name, placeholder: "Name of Activity", class: "form-control" %>
		<br>
		<%= f.text_field :units, placeholder: "What units to use?", class: "form-control" %>

		<%= f.submit "Create", class: "btn btn-default" %>
		<%= link_to "Cancel", [current_user, @activity], class: "btn btn-default" %>

	<% end %>

app/views/activities/new.html.erb
<div class="col-md-4 col-md-offset-4">
	<%= render 'users/new_activity' %>	
</div>

app/views/activities/new.js.erb
$(document).ready(function(){

	$("#toggle_new_activity").hide().after("<%= j render "new_activity" %>");
	
});

	
	

app/views/activities/show.html.erb
<div class="col-md-5">
		<h3>Entries (<%= @entries.count %>) </h3>
		<%= will_paginate @entries, inner_window: 0, outer_window: 0, previous_label: "<<", next_label: ">>"	%>
	<table class="table table-striped">	
		<thead>
			<tr>
				<th scope="col">Date</td>
				<th scope="col">Amount</td>
				<th scope="col"></td>
				<th scope="col"></td>
			</tr>
		</thead>
		<tbody>
			<% if @entries.any? %>
				<% @entries.each do |entry| %>
					<tr>
						<td><%= entry.date %></td>
						<td id="entry_<%= entry.id %>"><%= entry.units %>	[<%= @activity.units %>]</td>
						<td class="edit_entry_<%= entry.id %>"><%= link_to "Edit", edit_activity_entry_path(entry.activity, entry), remote: true %></td>
						<td><%= link_to "Delete", [entry.activity, entry], 
							method: :delete,		
							class: "text-danger",
							data: {confirm: "Are you sure?" }%></td>
					</tr>
				<% end %>
			<% else %>
				<tr>
					<td>You don't have any entries!</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div class="col-md-7">
	<br>
		<h3 class="text-center">Last Week's Data</h3>
		<%= line_chart @plot_data, xtitle: "Date", ytitle: @activity.units %>
<table class="table">
	<tr>
		<% @entries.each do |entry| %>
		<td class="text-center">
			<%= entry.date.strftime("%a") %>
		</td>
		<% end %>
	</tr>
	<tr>
		<% @entries.each do |entry| %>
			<td id="entry_<%= entry.id %>" class="text-center"><%= entry.units %></td>
		<% end %>		
	</tr>
	<tr>
		<% @entries.each do |entry| %>	
			<td class="edit_entry_<%= entry.id %>"><%= link_to "Edit", edit_activity_entry_path(entry.activity, entry), 
				class: "btn",
				remote: true %></td>
		<% end %>
	</tr>
</table>
</div>

app/views/entries/_edit.html.erb
<%= form_for [@activity,@entry], :remote => true do |f| %>
	<%= f.text_field :units, placeholder:@entry.units, class: "edit_entry_textbox" %>
	<%= f.submit "Save" %>
<% end %>
	

app/views/entries/edit.js.erb
$(function(){
	$("td#entry_<%= @entry.id %>").text('')
	$("td.edit_entry_<%= @entry.id %>").text('');
	$("td#entry_<%= @entry.id %>").append('<%= j render :partial => 'edit' %>');
	$(".edit_entry_textbox").focus().select();
});

app/views/entries/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<h2 class="text-centered">New Entry for <%= @activity.name %></h2>
	<%= form_for [@activity,@entry] do |f| %>
		<%= render 'shared/error_messages', object: @entry %>

		<%= f.label :date %>
		<%= f.date_field :date, class: "form-control", value: Date.today %>

		<%= f.label :amount %>
		<%= f.text_field :units, placeholder: @activity.units, class: "form-control" %>

		<%= f.submit "Add", class: "btn btn-default" %>
		<%= link_to "Cancel", [current_user, @activity], class: "btn btn-default" %>
	<% end %>
</div>

app/views/entries/update.js.erb
$(function(){
	$("#edit_entry_<%= @entry.id %>").html('');
	$("#edit_entry_<%= @entry.id %>").append(<%= "#{@entry.units}" %>);
	$(".edit_entry_<%= @entry.id %>").append('<%= link_to "Edit", edit_activity_entry_path(@activity, @entry), remote: true %>')

});

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse navbar-fixed-bottom">
		<div class="container">
    <div class="navbar-header">
        <button type="button" data-target="#footerCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="navbar-text">cjw development</div>
    </div>
    <!-- Collection of nav links and other content for toggling -->
		<div id="footerCollapse" class="collapse navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Contact", contact_path %></li>
				</ul>
		</div>
		</div>
</nav>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="container">
    <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">Creature of Habit</a>
    </div>
    <!-- Collection of nav links and other content for toggling -->
		<div id="navbarCollapse" class="collapse navbar-collapse">
			<% if logged_in? %>
				<% unless @activity.nil? %>
					<ul class="nav navbar-nav">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @activity.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Entry", new_activity_entry_path(@activity) %></li>
							<li><%= link_to "Edit", edit_activity_path(@activity) %></li>
							<li><%= link_to "Download Data", { format: :csv } %></li>
              <li><%= link_to "Delete", activity_path(@activity), method: :delete %></li>
            </ul>
						</li>
					</ul>
				<% end %>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Habits", current_user %></li>
					<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
					<li><%= link_to "Log Out", logout_path, method: :delete %></li>
				</ul>
			<% else %>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Log In", login_path %></li>
        </ul>
			<% end %>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
		<%= render 'layouts/head' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
			<div class="main col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1">
				<% flash.each do |message_type, message| %>
					<div class="alert alert-<%= message_type %>"><%= message %></div>
				<% end %>      			
				<%= yield %>
			</div>
		<%= render 'layouts/footer' %>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_login.html.erb
<h1 class="text-center">Log In</h1>
<div class="text-right">
	New? <%= link_to "Sign Up", signup_path %>
</div>
	
<%= form_for :session, url: login_path do |f| %>

	<%= f.label :email %>
	<%= f.email_field :email, class: "form-control" %>

	<%= f.label :password %>
	<%= f.password_field :password, class: "form-control" %>

	<%= f.submit "Log In", class: "btn btn-default" %>

<% end %>

app/views/shared/_new_activity.html.erb
<h3>New Activity</h3>

<%= form_for [@user,@activity] do |f| %>
	<%= render 'shared/error_messages', object: @activity %>

	<%= f.text_field :name, placeholder: "Name of Activity", class: "form-control" %>
	<br>
	<%= f.text_field :units, placeholder: "What units to use?", class: "form-control" %>

	<%= f.submit "Create", class: "btn btn-default" %>

<% end %>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>
<h1>About the "Habit Animal" App</h1>
<p>This is an app idea that I'm using to reaquire my Rails/Javascript and general webdev skills.</p>
<p>After the web based application is in good working order, I (we) are going to take it to mobile.</p>

app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>
<h1>Contact Us</h1>
<p>If you like the app or have suggestions please contact us: cjw7488 AT gmail.com</p>
<p>We're happy to hear from you!</p>

app/views/static_pages/home.html.erb
<div class="col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1">
	<div class="description">
		<p>We are all creatures of habit. Don't believe it?! Well, more and more <a href="https://www.psychologytoday.com/blog/creatures-habit/200907/we-are-creatures-habit">people are saying it</a>.</p>
		<p>The point is that our habits define us, and being able to have a better understanding of what we do can be insightful
		and interesting.</p>
		<p>That's the reason behind this app. Track your habits... good ones (exercise, teeth brushing, sleep) and bad ones (cigarrettes,
		nail bitting)</p>
		<p>Don't wait, start today! <%= link_to "Sign Up", signup_path %>
	</div>
</div>
<div class="col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1">
	<%= render 'shared/login' %>
</div>

app/views/users/edit.html.erb
<div class="col-md-4 col-md-offset-4">
	<h1 class="text-center">Edit Profile</h1>
	<%= form_for @user do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>

		<%= f.label :email %>
		<%= f.email_field :email, class: "form-control" %>

		<%= f.label :password %>
		<%= f.password_field :password, class: "form-control" %>

		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, class: "form-control" %>

		<%= f.submit "Update", class: "btn btn-default" %>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="col-md-4 col-md-offset-4">
	<h1 class="text-center">Sign Up</h1>
	
	<div class="text-right">
		Already a member? <%= link_to "Log In", login_path %>
	</div>

	<%= form_for @user do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>

		<%= f.label :email %>
		<%= f.email_field :email, class: "form-control" %>

		<%= f.label :password %>
		<%= f.password_field :password, class: "form-control" %>

		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, class: "form-control" %>

		<%= f.submit "Sign Up", class: "btn btn-default" %>

	<% end %>
</div>

app/views/users/show.html.erb
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
	<table class="table">
		<thead>
			<tr>
				<th scope="col"></th>
				<th scope="col">Tracking since:</th>
				<th scope="col"># Entries</th>
			</tr>
		</thead>

	<% if @activities.any? %>
			<% @activities.each do |activity| %>
					<tr>
						<td><%= link_to "#{activity.name} [#{activity.units}]", [activity.user, activity] %></td>
						<% if activity.entries.empty? %>
							<td></td>
							<td></td>
						<% else %>
							<td><%= activity.entries.order(:date).first.date %></td>
							<td><%= activity.entries.count %></td>
						<% end %>
					</tr>
			<% end %>
	<% else %>
		<tr>
			<td>You aren't tracking any activities!</td>
			<td></td>
			<td></td>
		</tr>
	<% end %>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	</table>
	<%= link_to "Add New", new_user_activity_path(current_user), remote: true, id: "toggle_new_activity" %>
</div>